### PR TITLE
Error Handling in `MainMenuScreen`

### PR DESCRIPTION
**Pull request by newtaDev**
if user did not sign in to `GamesServicesController` and if pressed on `Achievements` or `Leaderboard` button in `MainMenuScreen`

Before:
        - shows error in console
        - nothing shows in UI

After:
        - shows error in console
        - shows `Error snackBar` in UI

### CODE REVIEW

**Review by filiph — APPROVED** [review]
Oh, sweet! Thank you!

**Comment by newtaDev** [comment]
Hey @filiph,
Can I work more on the error handling part?
Like catching exceptions, when there is no internet connection or if any other unexpected exceptions thrown

**Comment by filiph** [comment]
Well, I'd leave unexpected exceptions to Crashlytics, so that I get to know about them. But if you see some exceptions that really _should_ be expected, and aren't, go ahead!

**Comment by newtaDev** [comment]
> Oh, sweet! Thank you!

Thank you for creating this awesome game 🔥🔥

**Comment by newtaDev** [comment]
> Well, I'd leave unexpected exceptions to Crashlytics, so that I get to know about them. But if you see some exceptions that really _should_ be expected, and aren't, go ahead!

Okay, Let me give it a try

**Pull request merged**
